server :
    port: 8084

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
logging:
  level:
    org.springframework: INFO
    ma.pfe: ERROR
    org.hibernate: ERROR
    org.apache: ERROR
    com.zaxxer: ERROR